some minor adjustments
newrelic-experimental/newrelic-social-listening-service-nodejs pull request #27
Opened 2021-03-09 05:52 UTC by harrykimpel

2021-03-26 14:00 UTC, matewilk requested changes

2021-03-26 14:00 UTC, matewilk commented on README.md
>  Send a POST request to the following endpoint:
Change to `GET` as well please.

2023-04-25 14:47 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/newrelic-experimental/newrelic-social-listening-service-nodejs?pullRequest=27) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/newrelic-experimental/newrelic-social-listening-service-nodejs?pullRequest=27) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/newrelic-experimental/newrelic-social-listening-service-nodejs?pullRequest=27) it.</sub>

2023-04-26 13:03 UTC, harrykimpel commented on README.md
>  Send a POST request to the following endpoint:
@matewilk changed this as well

2023-04-27 15:02 UTC, matewilk reviewed
Thanks for the correction!

2023-04-28 09:05 UTC, matewilk approved these changes

2023-04-28 09:08 UTC, merged